parameters:
    app.name: 'Teamspeak3 Channel Watcher'
    app.version: '0.1'

services:
    command.database.create_table:
      class: \devmx\ChannelWatcher\Command\CreateDataBaseCommand
      calls:
        - [setContainer, ['@service_container']]
    command.crawl:
      class: \devmx\ChannelWatcher\Command\CrawlCommand
      calls:
        - [setContainer, ['@service_container']]
    command.print_unused:
       class: \devmx\ChannelWatcher\Command\PrintUnusedCommand
       calls:
        - [setContainer, ['@service_container']]
    application:
      class: \Symfony\Component\Console\Application
      arguments: ['%app.name%', '%app.version%']
      calls:
        - [ add, ['@command.crawl']]
        - [ add, ['@command.database.create_table']]
        - [ add, ['@command.print_unused']]
        - [setAutoExit, [false]]