services:
  crawler:
    class: \devmx\ChannelWatcher\ChannelCrawler
    arguments: ['@teamspeak.query', '@storage']
  storage:
    class: \devmx\ChannelWatcher\Storage\DbalStorage\DbalStorage
    arguments: ['@dbal.connection', '%dbal.tablename%']
    
      