parameters:
  dbal.sqlite.filename: channels.sqlite
  dbal.charset: utf8
  dbal.connection.class: \Doctrine\DBAL\Connection
  dbal.connection.factory_class: \Doctrine\DBAL\DriverManager
  dbal.tablename: %dbal.prefix%channels
  #dbal.connection.additional_params: 
   # wrapperClass: Doctrine\DBAL\Portability\Connection,
    #portability: \Doctrine\DBAL\Portability\Connection::PORTABILITY_ALL,
    #fetch_case: \PDO::CASE_LOWER
services:
  dbal.configuration:
    class: \Doctrine\DBAL\Configuration
  dbal.connection:
    class: %dbal.connection.class%
    factory_class: %dbal.connection.factory_class%
    factory_method: getConnection
    arguments: 
      - '%dbal.connection.parameter%'
      - '@dbal.configuration'
  dbal.manager:
    class: \devmx\ChannelWatcher\Storage\DbalStorage\DataBaseManager

    
    
  