services:
  teamspeak.transmission:
    class: \devmx\Transmission\TCP
    arguments: ['%teamspeak.host%', '%teamspeak.port%', 5, 0]
  teamspeak.commandtranslator:
    class: \devmx\Teamspeak3\Query\Transport\Common\CommandTranslator
  teamspeak.responsehandler:
    class: \devmx\Teamspeak3\Query\Transport\Common\ResponseHandler
  teamspeak.transport.base:
    class: \devmx\Teamspeak3\Query\QueryTransport
    arguments: ['@teamspeak.transmission', '@teamspeak.commandtranslator', '@teamspeak.responsehandler']
  teamspeak.query:
    class: \devmx\Teamspeak3\Query\ServerQuery
    arguments: ['@teamspeak.transport']
    calls:
      - [connect , [] ]
      - [useByPort, ['%teamspeak.vserver.port%']]
