## travis-ci.org configuration
language: php
php:
  - 5.3
  - 5.4

env:
  - DB=sqlite
  - DB=mysqli
  - DB=pgsql

before_script:

    - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS devmx_channelwatcher_tests;' -U postgres; fi"
    - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'DROP DATABASE IF EXISTS devmx_channelwatcher_tests_tmp;' -U postgres; fi"
    - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database devmx_channelwatcher_tests;' -U postgres; fi"
    - sh -c "if [ '$DB' = 'pgsql' ]; then psql -c 'create database devmx_channelwatcher_tests_tmp;' -U postgres; fi"
    - sh -c "if [ '$DB' = 'mysqli' ]; then mysql -e 'create database IF NOT EXISTS devmx_channelwatcher_tests_tmp;create database IF NOT EXISTS devmx_channelwatcher_tests;'; fi"
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar --dev install

script: phpunit --configuration tests/travis-config/$DB.travis.xml
