<?php

namespace devmx\ChannelWatcher\Storage;

require_once dirname( __FILE__ ) . '/../../../../../src/devmx/ChannelWatcher/Storage/InMemoryStorage.php';

/**
 * Test class for InMemoryStorage.
 * Generated by PHPUnit on 2012-01-30 at 11:40:37.
 */
class InMemoryStorageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var \devmx\ChannelWatcher\Storage\InMemoryStorage
     */
    protected $storage;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->storage = new InMemoryStorage();
    }

   
    /**
     * @covers devmx\ChannelWatcher\Storage\InMemoryStorage::update
     * @covers devmx\ChannelWatcher\Storage\InMemoryStorage::getChannels
     */
    public function testUpdate()
    {
        //first run
        $this->storage->update(1, true, 123);
        $this->storage->update(2, false, 123);
        $this->assertEquals(array(1=>123, 2=>123), $this->storage->getChannels());
        //second run
        $this->storage->update(1, false, 234);
        $this->storage->update(2, true, 234);
        $this->assertEquals(array(1=>123, 2=>234), $this->storage->getChannels());
    }

    /**
     * @covers devmx\ChannelWatcher\Storage\InMemoryStorage::getChannelsEmptyFor
     * @todo Implement testGetChannelsEmptyFor().
     */
    public function testGetChannelsEmptyFor()
    {
        $this->storage->update(12, true, 123);
        $this->storage->update(13, true, 234);        
        $this->assertEquals(array(12), $this->storage->getChannelsEmptyFor(5, 235 ));
    }

}

?>
