<?php

namespace devmx\ChannelWatcher\Tests\Rule;

use devmx\ChannelWatcher\Rule\SaveDefaultChannelRule;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-07-29 at 18:05:55.
 */
class SaveDefaultChannelRuleTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @covers devmx\ChannelWatcher\Rule\SaveDefaultChannelRule
     */
    public function testFilter()
    {
        $rule = new SaveDefaultChannelRule();

        $channels = array(
             1 => array(
               'cid' => 1,
               'channel_flag_default' => 1,
               '__delete' => true
             ),
             2 => array(
                 'cid' => 2,
                 'channel_flag_default' => 0,
                 '__delete' => true
             ),
        );

        $expected = $channels;
        $expected[1]['__delete'] = false;

        $this->assertEquals($expected, $rule->filter($channels));
    }

}
